-- BMW Rental System - Database Schema
-- Run: psql -d bmw_rental_system -f schema.sql

CREATE TABLE IF NOT EXISTS public.users (
  user_id     SERIAL PRIMARY KEY,
  full_name   VARCHAR(100) NOT NULL,
  email       VARCHAR(100) NOT NULL UNIQUE,
  phone       VARCHAR(20),
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  role        VARCHAR DEFAULT 'user',
  password    VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.cars (
  car_id        SERIAL PRIMARY KEY,
  car_code      VARCHAR(50) NOT NULL UNIQUE,
  name          VARCHAR(100) NOT NULL,
  series        VARCHAR(100),
  type          VARCHAR(50),
  price_per_day NUMERIC(8,2) NOT NULL,
  hp            VARCHAR(50),
  speed         VARCHAR(50),
  description   TEXT,
  image_url     TEXT
);

CREATE TABLE IF NOT EXISTS public.reservations (
  reservation_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id        INTEGER NOT NULL,
  car_id         INTEGER NOT NULL,

  pickup_date    TIMESTAMPTZ NOT NULL,
  pickup_time    VARCHAR(20),
  return_date    TIMESTAMPTZ NOT NULL,
  return_time    VARCHAR(20),

  total_price    NUMERIC(10,2) NOT NULL,
  status         VARCHAR(20) DEFAULT 'pending',
  admin_note     TEXT,
  created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT reservations_status_check
    CHECK (status IN ('pending', 'approved', 'rejected')),

  CONSTRAINT reservations_user_fk
    FOREIGN KEY (user_id) REFERENCES public.users(user_id)
    ON DELETE CASCADE,

  CONSTRAINT reservations_car_fk
    FOREIGN KEY (car_id) REFERENCES public.cars(car_id)
    ON DELETE RESTRICT
);

-- Helpful indexes
CREATE INDEX IF NOT EXISTS idx_reservations_user_id ON public.reservations(user_id);
CREATE INDEX IF NOT EXISTS idx_reservations_car_id  ON public.reservations(car_id);
CREATE INDEX IF NOT EXISTS idx_reservations_created ON public.reservations(created_at);
